### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by richiksc**

### CODE REVIEW

**Comment by Windwoes** [comment]
@richiksc  Well there are a few issues with this - the first being since you've nuked the action bar there's now no way to open the overflow menu.

**Comment by richiksc** [comment]
@FROGbots-4634 When I first ran it I never saw an action bar. I believe that from Android versions 6+ the action bar is not visible by default. I have added a menu button in my later commit.

**Comment by Windwoes** [comment]
@richiksc well that's odd because I had been testing on a Nexus 5 running Android 7.1.1 (Lineage OS custom ROM) so maybe you had accidentally changed something before testing.

**Comment by Windwoes** [comment]
Ok so the next issue is that you've introduced a bug where if you add some scores and then open and close the About activity, the summary section at the bottom gets cut off...

**Comment by richiksc** [comment]
@FROGbots-4634 I was testing on Android 8.0 emulator as well as my Nexus 5X running Oreo, sorry. I'll check the About activity issue.

**Comment by Windwoes** [comment]
@richiksc any update on this?

**Comment by richiksc** [comment]
Sorry, didn't work over winter break and didn't really get back to this.
Great app by the way, we use it a lot!

**Pull request closed without merging**
